#ifdef PBL_COLOR
#define CalendarFGColor GColorBlack
#define CalendarBGColor GColorPastelYellow
#define CalendarHeadFGColor GColorPastelYellow
#define CalendarHeadBGColor GColorDukeBlue
#define CalendarSelFGColor GColorBlack
#define CalendarSelBGColor GColorVividCerulean
#define TimeColor GColorPastelYellow
#define TimeOutlineColor GColorBlack
#define SecondColor GColorPastelYellow
#define SecondOutlineColor GColorBlack
#define DateColor GColorPastelYellow
#define DateOutlineColor GColorBlack
#define WeatherCityColor GColorWhite
#define WeatherTempNowColor GColorWhite
#define WeatherDaysColor GColorWhite
#define WeatherTempHighColor GColorMelon
#define WeatherTempLowColor GColorCeleste
#define UpdatedColor GColorWhite
#define SunriseColor GColorPastelYellow
#define SunsetColor GColorPictonBlue
#define PhaseColor GColorWhite
#define ZodiacColor GColorWhite
#else
#define CalendarFGColor GColorBlack
#define CalendarBGColor GColorWhite
#define CalendarHeadFGColor GColorWhite
#define CalendarHeadBGColor GColorBlack
#define CalendarSelFGColor GColorWhite
#define CalendarSelBGColor GColorWhite
#define TimeColor GColorWhite
#define SecondColor GColorWhite
#define DateColor GColorWhite
#define WeatherCityColor GColorWhite
#define WeatherTempNowColor GColorWhite
#define WeatherDaysColor GColorWhite
#define WeatherTempHighColor GColorWhite
#define WeatherTempLowColor GColorWhite
#define UpdatedColor GColorWhite
#define SunriseColor GColorWhite
#define SunsetColor GColorWhite
#define PhaseColor GColorWhite
#define ZodiacColor GColorWhite
#endif
